hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("dunst")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon && awww img ../../../../../assets/wallpapers/waves.jpg")
    hl.exec_cmd("pypr")
    hl.exec_cmd("gammastep -b 1:1")
    hl.exec_cmd("activate-linux -f 'Noto Sans'")
    hl.exec_cmd("openrgb -p default")

    hl.exec_cmd("vesktop", { workspace = "1 silent" })
    hl.exec_cmd("zen-twilight", { workspace = "2 silent" })
    hl.exec_cmd("codium", { workspace = "3 silent" })
    hl.exec_cmd("thunar", { workspace = "special:preload silent" })
end)
