{
  config,
  lib,
  pkgs,
  ...
}:
{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./crosscompilation.nix
    ./docker.nix
    ./gaming.nix
    ./powerprofiles/laptop.nix
    ./powerprofiles/server.nix
    ./printing.nix
    ./syncthing.nix
    ./trackpad.nix
    ./wireshark.nix
    ./filemanager.nix
    ./plymouth.nix
    ./udev.nix
  ];
}
