# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{
  fetchurl,
}:

self: super: {
  "certifi" = super.buildPythonPackage {
    pname = "certifi";
    version = "2025.8.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/48/1549795ba7742c948d2ad169c1c8cdbae65bc450d6cd753d124b17c8cd32/certifi-2025.8.3-py3-none-any.whl";
      sha256 = "198pyad6jy7x5wx5v3ln8ik5vijhjfprb19jzyi6pc5iry9j9hgn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "charset-normalizer" = super.buildPythonPackage {
    pname = "charset-normalizer";
    version = "3.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/2d/5fd176ceb9b2fc619e63405525573493ca23441330fcdaee6bef9460e924/charset_normalizer-3.4.3.tar.gz";
      sha256 = "054d0r8rimd5wrcph6p7p2dblcni614llpa6f75nykr4022lpkkg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "click" = super.buildPythonPackage {
    pname = "click";
    version = "7.1.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl";
      sha256 = "1p607168jqq20d8bngrkfqv0vvkfas57r6s8szimvpgs9fgsik6s";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "compal" = super.buildPythonPackage {
    pname = "compal";
    version = "0.3.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bb/6d/e838cc8c04f3923b9979aab4d983c514d9c70efb0627e273938dd8ef12c7/compal-0.3.1.tar.gz";
      sha256 = "1a068zyrsczmvrpsj3lj6jg81mqx03p7w271cbq9bhwghf3xjm1x";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."lxml"
      self."requests"
    ];
  };
  "deepmerge" = super.buildPythonPackage {
    pname = "deepmerge";
    version = "0.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/72/89/3c310fb23c96ef2dcf8bab59dc500f53a06a1dd6d05ceec217331b097962/deepmerge-0.2.1-py2.py3-none-any.whl";
      sha256 = "1cq1kmflswg3bniiybicv9srginc9fziijrnc9l4kqpvhlgr0w42";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "idna" = super.buildPythonPackage {
    pname = "idna";
    version = "3.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/c6/c88e154df9c4e1a2a66ccf0005a88dfb2650c1dffb6f5ce603dfbd452ce3/idna-3.10-py3-none-any.whl";
      sha256 = "1lw72a5swas501zvkpd6dsryj5hzjijqxs3526kbp7151md1jvcl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "lxml" = super.buildPythonPackage {
    pname = "lxml";
    version = "6.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/ed/60eb6fa2923602fba988d9ca7c5cdbd7cf25faa795162ed538b527a35411/lxml-6.0.0.tar.gz";
      sha256 = "0wpv07m2k2w9pzyw2dd5yc2p4pqgcsgnqcpw7vf4rm1r0c96abh3";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "prometheus-client" = super.buildPythonPackage {
    pname = "prometheus-client";
    version = "0.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f4/7e/ef341c67ed43ad2e39633a35c28b77bc555f9572f4df4fee11c2b467db00/prometheus_client-0.9.0-py2.py3-none-any.whl";
      sha256 = "0d9xd7jcnqpgjrr9pq47l2s4bwf8wrl2cddly1hmkgz1531k935h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "requests" = super.buildPythonPackage {
    pname = "requests";
    version = "2.32.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7c/e4/56027c4a6b4ae70ca9de302488c5ca95ad4a39e190093d6c1a8ace08341b/requests-2.32.4-py3-none-any.whl";
      sha256 = "0b1bmhqv0xarifclr53icqwpsw1hk3l4w8230jrm0v9av8ybvfi7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "ruamel.yaml" = super.buildPythonPackage {
    pname = "ruamel.yaml";
    version = "0.16.13";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/c3/4c823dac2949a6baf36a4987d04c50d30184147393ba6f4bfb4c67d15a13/ruamel.yaml-0.16.13-py2.py3-none-any.whl";
      sha256 = "18wm5vkflncvrnkr5jmdihv8dms7ahsggkjya8ji33pbfdw6xc34";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."ruamel.yaml.clib"
    ];
  };
  "ruamel.yaml.clib" = super.buildPythonPackage {
    pname = "ruamel.yaml.clib";
    version = "0.2.12";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/84/80203abff8ea4993a87d823a5f632e4d92831ef75d404c9fc78d0176d2b5/ruamel.yaml.clib-0.2.12.tar.gz";
      sha256 = "0vykvxpmiv4s0f3k2f97slf99rvsn3h4daq136lrjgshxh9vp3vc";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "urllib3" = super.buildPythonPackage {
    pname = "urllib3";
    version = "2.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a7/c2/fe1e52489ae3122415c51f387e221dd0773709bad6c6cdaa599e8a2c5185/urllib3-2.5.0-py3-none-any.whl";
      sha256 = "1p7hrw2cc75zyqbb49diqi371gxkis07225mfkii6spsq1ridc76";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
}
