{
  ...
}:
{
  imports = [
    ./media
    ./servers/factorio.nix
    ./servers/mowie.nix
    ./servers/minecraft.nix
    ./servers/chatger/chatger.nix
    ./servers/chatger/chatger-registry.nix
    ./network/ddns/ddns.nix
    ./network/acme.nix
    ./network/blocky.nix
    ./network/reverse-proxy/caddy.nix
    ./network/reverse-proxy/nginx.nix
    ./network/headscale/headscale.nix
    ./network/pihole.nix
    ./network/fail2ban.nix
    ./auth/authelia.nix
    ./auth/lldap.nix
    ./observability/grafana.nix
    ./observability/prometheus.nix
    ./observability/promtail.nix
    ./observability/loki.nix
    ./observability/gatus.nix
    ./observability/metabase.nix
    ./scraping/iss-piss-stream.nix
    ./scraping/connectbox/connectbox.nix
    ./sync/atuin.nix
    ./sync/anki.nix
    ./vaultwarden.nix
    ./filebrowser.nix
    ./immich.nix
    ./linkwarden.nix
    ./nextcloud.nix
    ./homepage.nix
    ./microbin.nix
    ./httpbin.nix
    ./githubrunners.nix
    ./attic.nix
  ];
}
