{
  config,
  lib,
  pkgs,
  ...
}:
{
  imports = [
    ./media
    ./network/ddns/ddns.nix
    ./network/acme.nix
    ./network/blocky.nix
    ./network/caddy.nix
    ./network/headscale.nix
    ./auth/authelia.nix
    ./auth/lldap.nix
    ./observability/grafana.nix
    ./observability/prometheus.nix
    ./observability/promtail.nix
    ./observability/loki.nix
    ./observability/gatus.nix
    ./scraping/iss-piss-stream.nix
    ./sync/atuin.nix
    ./sync/anki.nix
    ./sync/vaultwarden.nix
    ./web/filebrowser.nix
    ./web/immich.nix
    ./web/linkwarden.nix
    ./web/nextcloud.nix
  ];
}
