{
  config,
  lib,
  pkgs,
  ...
}:
{
  imports = [
    ./media
    ./domains.nix
    ./ddns/ddns.nix
    ./acme.nix
    ./caddy.nix
    ./immich.nix
    ./iss-piss-stream.nix
    ./minecraft.nix
    ./blocky.nix
    ./headscale.nix
    ./atuin.nix
    ./syncthing.nix
    ./nextcloud.nix
    ./atuin.nix
    ./observability/grafana.nix
    ./observability/prometheus.nix
    ./observability/promtail.nix
    ./observability/loki.nix
  ];
}
